version: '3'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: go-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always